<template>
  <div class="main-logos">
    <img
      data-src="/img/main-logo1.svg"
      src="data:image/gif;base64,R0lGODlhAQABAAAAACw="
      class="js-img"
      alt=""
    />
    <img
      data-src="/img/main-logo2.svg"
      src="data:image/gif;base64,R0lGODlhAQABAAAAACw="
      class="js-img"
      alt=""
    />
    <img
      data-src="/img/main-logo3.svg"
      src="data:image/gif;base64,R0lGODlhAQABAAAAACw="
      class="js-img"
      alt=""
    />
    <img
      data-src="/img/main-logo4.svg"
      src="data:image/gif;base64,R0lGODlhAQABAAAAACw="
      class="js-img"
      alt=""
    />
    <img
      data-src="/img/main-logo5.svg"
      src="data:image/gif;base64,R0lGODlhAQABAAAAACw="
      class="js-img"
      alt=""
    />
  </div>
</template>
